openapi: 3.0.0
info:
  title: Feedback API
  version: 1.0.0
paths:
  /feedback/create-feedback:
    post:
      tags: [Feedback]
      summary: Create feedback
      description: Creates a new feedback entry.
      requestBody:
        description: Feedback details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@mail.com
                name:
                  type: string
                  example: John Doe
                message:
                  type: string
                  example: 'This is a feedback message.'
              required: [email, name, message]
      responses:
        '201':
          description: Feedback created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  email:
                    type: string
                    format: email
                    example: user@mail.com
                  name:
                    type: string
                    example: John Doe
                  message:
                    type: string
                    example: 'This is a feedback message.'
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Bad request error occurred'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Internal server error occurred'

components:
  responses:
    BadRequest:
      description: Bad request error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Bad request error occurred'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Internal server error occurred'
